---
name: add_policies_to_ci_job_token
feature_issue_url: https://gitlab.com/gitlab-org/govern/authorization/team-tasks/-/issues/69
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/167872
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/497754
milestone: '17.5'
group: group::authorization
type: wip
default_enabled: false
