---
name: stacked_merge_requests
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/592303
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/231697
rollout_issue_url:
milestone: '18.11'
group: group::code review
type: wip
default_enabled: false
