---
name: todos_snoozing
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/17712
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175163
rollout_issue_url:
milestone: '17.7'
group: group::personal productivity
type: wip
default_enabled: false
