---
name: use_websocket_for_k8s_watch
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/13380
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/168399
rollout_issue_url:
milestone: '17.5'
group: group::environments
type: wip
default_enabled: false
