include:
  - local: gems/gem.gitlab-ci.yml
    inputs:
      bundle_gemfiles: ['Gemfile', 'Gemfile.next']
      gem_name: "gitlab-backup-cli"


rspec:
  extends: .ruby_on_rails_matrix
  variables:
    BUNDLE_FROZEN: "false"
    POSTGRES_USER: gitlab
    POSTGRES_PASSWORD: password
    POSTGRES_VERSION: 14
    PGPASSWORD: "${POSTGRES_PASSWORD}"
  services:
    - name: postgres:${POSTGRES_VERSION}
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
  before_script:
    - cp gems/gitlab-backup-cli/spec/fixtures/config/database.yml config/
    - "sed -i \"s/username: postgres$/username: $POSTGRES_USER/g\" config/database.yml"
    - "sed -i \"s/password:\\s*$/password: $POSTGRES_PASSWORD/g\" config/database.yml"
    - "sed -i \"s/host: localhost$/host: postgres/g\" config/database.yml"
    - apt update && apt install -y postgresql-client
    - psql -h postgres -U $POSTGRES_USER -c 'create database gitlabhq_test;'
    - psql -h postgres -U $POSTGRES_USER -c 'create database gitlabhq_ci_test;'
    - !reference [.default, before_script]
  script:
    - RAILS_ENV=test bundle exec rspec
  coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
  artifacts:
    expire_in: 31d
    when: always
    paths:
      - coverage/
