---
name: by_pass_two_factor_for_current_session
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122109
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/416535
milestone: '16.3'
type: development
group: group::authentication
default_enabled: true
