---
name: change_namespace_default_role_for_pipeline_variables
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/171424
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/502238
milestone: '17.7'
type: development
group: group::pipeline security
default_enabled: false
