---
name: enable_add_on_users_filtering
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136858
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431365
milestone: '16.7'
type: development
group: group::provision
default_enabled: true
