---
name: global_file_size_check
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/125956
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/418995
milestone: '16.2'
type: development
group: group::source code
default_enabled: false
