---
api_type: boolean
attr: elasticsearch_aws
clusterwide: false
column: elasticsearch_aws
db_type: boolean
default: 'false'
description: Enable the use of AWS hosted Elasticsearch. Premium and Ultimate only.
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
