---
api_type: integer
attr: elasticsearch_indexed_file_size_limit_kb
clusterwide: false
column: elasticsearch_indexed_file_size_limit_kb
db_type: integer
default: '1024'
description: Maximum size of repository and wiki files that are indexed by Elasticsearch.
  Premium and Ultimate only.
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
