---
api_type: string
attr: elasticsearch_username
clusterwide: false
column: elasticsearch_username
db_type: text
default:
description: The `username` of your Elasticsearch instance. Premium and Ultimate only.
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: false
