---
api_type:
attr: elasticsearch
clusterwide: false
column: elasticsearch
db_type: jsonb
default: "'{}'::jsonb"
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
