---
api_type: boolean
attr: elasticsearch_limit_indexing
clusterwide: false
column: elasticsearch_limit_indexing
db_type: boolean
default: 'false'
description: Limit Elasticsearch to index certain namespaces and projects. Premium
  and Ultimate only.
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
