---
api_type:
attr: elasticsearch_pause_indexing
clusterwide: false
column: elasticsearch_pause_indexing
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
