---
api_type:
attr: elasticsearch_analyzers_kuromoji_enabled
clusterwide: true
column: elasticsearch_analyzers_kuromoji_enabled
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
