---
api_type:
attr: lock_npm_package_requests_forwarding
clusterwide: false
column: lock_npm_package_requests_forwarding
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
