---
api_type:
attr: oauth_provider
clusterwide: true
column: oauth_provider
db_type: jsonb
default: "'{}'::jsonb"
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
