---
api_type:
attr: observability_settings
clusterwide: false
column: observability_settings
db_type: jsonb
default: "'{}'::jsonb"
description: Contains application settings for Observability features
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
