---
api_type:
attr: packages_cleanup_package_file_worker_capacity
clusterwide: false
column: packages_cleanup_package_file_worker_capacity
db_type: smallint
default: '2'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
