---
api_type: boolean
attr: pre_receive_secret_detection_enabled
clusterwide: true
column: pre_receive_secret_detection_enabled
db_type: boolean
default: 'false'
description: Allow projects to enable secret push protection. This does not enable
  secret push protection. When you enable this feature, you accept the [GitLab Testing
  Agreement](https://handbook.gitlab.com/handbook/legal/testing-agreement/). Ultimate
  only.
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
