---
api_type:
attr: secret_detection_service_auth_token
clusterwide: false
column: encrypted_secret_detection_service_auth_token
db_type: bytea
default:
description: The authentication token to connect to the Secret Detection Service
encrypted: true
gitlab_com_different_than_default: false
jihu: false
not_null: false
