---
api_type:
attr: secret_detection_service_url
clusterwide: false
column: secret_detection_service_url
db_type: text
default: "''::text"
description: Stores the URL to connect to the Secret Detection Service
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
