---
api_type:
attr: security_policy_scheduled_scans_max_concurrency
clusterwide: false
column: security_policy_scheduled_scans_max_concurrency
db_type: integer
default: '10000'
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
