---
api_type: boolean
attr: show_migrate_from_jenkins_banner
clusterwide: false
column: show_migrate_from_jenkins_banner
db_type: boolean
default: 'true'
description: Show the migrate from jenkins banner
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
