---
name: application_rate_limiter_static_labkit_limiters
description: Use static Labkit limiter objects for ApplicationRateLimiter checks
feature_issue_url: https://gitlab.com/gitlab-com/gl-infra/production-engineering/-/work_items/29054
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/242446
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/604963
milestone: '19.2'
group: group::networking and incident management
type: gitlab_com_derisk
default_enabled: false
