---
name: auto_merge_train_elaborate_abort_msg
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/467300
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165581
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/500079
milestone: '17.6'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
