---
name: block_banned_user_normalized_email_reuse
feature_issue_url: https://gitlab.com/gitlab-org/modelops/anti-abuse/team-tasks/-/issues/815
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/161122
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/474964
milestone: '17.3'
group: group::anti-abuse
type: gitlab_com_derisk
default_enabled: false
