---
name: drop_lease_usage_authorized_projects_worker
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/484754
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/169381
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/499429
milestone: '17.6'
group: group::authorization
type: gitlab_com_derisk
default_enabled: false
