---
name: drop_lease_usage_project_recalculate_workers
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/484754
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/172948
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/506346
milestone: '17.7'
group: group::authorization
type: gitlab_com_derisk
default_enabled: false
