---
name: fix_pages_ci_variables
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/416493
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165922
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/503993
milestone: '17.7'
group: group::knowledge
type: gitlab_com_derisk
default_enabled: false
