---
name: importer_user_mapping_reassignment_csv
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/455906
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/162267
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/478022
milestone: '17.4'
group: group::import and integrate
type: gitlab_com_derisk
default_enabled: false
