---
name: lfs_misconfiguration_banner
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429467
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/162123
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/477892
milestone: '17.4'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
