---
name: loose_foreign_keys_for_polymorphic_associations
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/341515
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/172412
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/505647
milestone: '17.7'
group: group::security infrastructure
type: gitlab_com_derisk
default_enabled: false
