---
name: merge_request_detailed_failure_reasons
description: Adds the reason for each failed mergeability check to the "Merge request is not mergeable" error.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594774
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/226126
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594769
milestone: '19.2'
group: group::code review
type: gitlab_com_derisk
default_enabled: false
