---
name: packages_protected_packages_conan
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323975
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/168224
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/497811
milestone: '17.6'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
