---
name: packages_allow_duplicate_exceptions
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/482901
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165467
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/498085
milestone: '17.7'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
