---
name: pat_organization_filter
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/486037
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165620
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/486988
milestone: '17.4'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
