---
name: pats_expiring_worker_extended_logging
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/506438
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/174791
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/509375
milestone: '17.8'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
