---
name: review_merge_request_dap_model_config
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/598179
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/236876
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/600605
milestone: '19.1'
group: group::ai coding
type: gitlab_com_derisk
default_enabled: false
