---
name: toggle_redis_6_0_compatibility
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/506384
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/176184
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/511346
milestone: '17.8'
group: group::optimize
type: gitlab_com_derisk
default_enabled: false
