---
name: use_primary_store_as_default_for_db_load_balancing
feature_issue_url: https://gitlab.com/gitlab-com/gl-infra/data-access/durability/team/-/issues/39
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175822
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/509562
milestone: '17.8'
group: group::durability
type: gitlab_com_derisk
default_enabled: false
