---
name: work_item_created_flow_trigger
description: This feature flag is scoped to the Project level. If enabled, the work_item_created trigger event is shown to customers.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/599985
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/239419
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/602180
milestone: '19.1'
group: group::ai coding
type: gitlab_com_derisk
default_enabled: false
