---
description: User visited credentials inventory page in the Admin area
action: visit_compliance_credential_inventory
internal_events: true
identifiers:
- user
product_group: authentication
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107120
tiers:
- ultimate
