description: Enable manual prometheus
category: cluster:services:prometheus
action: enabled_manual_prometheus
extra_properties:
identifiers:
product_group: import_and_integrate
milestone: "14.0"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/62645
tiers:
- free
- premium
- ultimate
