---
description: When a pipeline is created with a CI Template file included in its configuration.
internal_events: true
action: ci_template_included
extra_properties:
identifiers:
- project
- user
- namespace
product_group: pipeline_authoring
milestone: "16.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132819
tiers:
- free
- premium
- ultimate
