---
description: Project runner created
internal_events: true
action: click_create_project_runner_button
identifiers:
  - project
  - namespace
  - user
product_group: runner
milestone: '16.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146063
tiers:
  - free
  - premium
  - ultimate
