---
name: bitbucket_import_resumable_worker
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/466231
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/156797
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/471309
milestone: '17.3'
group: group::import and integrate
type: beta
default_enabled: false
