---
name: oauth2_device_grant_flow
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/332682
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155622
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/468479
milestone: '17.1'
group: group::authentication
type: beta
default_enabled: true
