---
name: search_button_top_right
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/480341
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141513
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/18537
milestone: '17.5'
group: group::global search
type: beta
default_enabled: false
