inherit_from:
  - ../config/rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - lib/gitlab/secret_detection/grpc/generated/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

RSpec/MultipleMemoizedHelpers:
  Max: 25
