---
key_path: counts.instances_gitlab_slack_application_active
description: Count instances with active slack application
product_group: import_and_integrate
product_categories:
- integrations
value_type: number
status: active
milestone: "14.3"
introduced_by_url: https://gilab.com/gitlab-org/gitlab/-/merge_requests/70496
time_frame: all
data_source: database
data_category: optional
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
