---
key_path: counts.groups_inheriting_zentao_active
description: Count of groups that inherit active Zentao integrations
product_group: import_and_integrate
product_categories:
- integrations
value_type: number
status: active
milestone: "14.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/338178
time_frame: all
data_source: database
data_category: operational
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
