---
data_category: optional
key_path: counts.web_hooks
description: Count of web hooks
product_group: import_and_integrate
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
