---
data_category: optional
key_path: counts.projects_inheriting_drone_ci_active
description: Count of active projects inheriting integrations for Drone CI
product_group: import_and_integrate
product_categories:
- integrations
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
