---
key_path: counts.slack_app_installations
description: Count of Slack app installations
product_group: import_and_integrate
value_type: number
status: active
milestone: "15.1"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89130
time_frame: all
data_source: database
data_category: optional
instrumentation_class: CountSlackAppInstallationsMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
