---
data_category: optional
key_path: counts.instances_diffblue_cover_active
description: Count of active instance-level integrations for Diffblue Cover
product_group: import_and_integrate
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "16.8"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
