---
key_path: counts.projects_inheriting_squash_tm_active
description: Count of active projects inheriting integrations for Squash TM
product_group: import_and_integrate
product_categories:
- integrations
value_type: number
status: active
milestone: "15.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110909
time_frame: all
data_source: database
data_category: optional
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
