---
key_path: counts.groups_inheriting_telegram_active
description: Count of active groups inheriting integrations for Telegram
product_group: import_and_integrate
value_type: number
status: active
milestone: "16.1"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122879
time_frame: all
data_source: database
data_category: optional
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
