---
key_path: counts.groups_inheriting_jira_cloud_app_active
description: Count of active groups inheriting integrations for Jira Cloud App
product_group: import_and_integrate
value_type: number
status: active
milestone: "17.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/154634
time_frame: all
data_source: database
data_category: optional
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
