---
key_path: counts.orphaned_namespaces
description: Whether orphaned namespaces are present
product_group: organizations
value_type: number
status: active
milestone: "17.6"
instrumentation_class: OrphanedNamespacesMetric
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/168983
time_frame: all
data_source: database
data_category: optional
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
