---
migration_job_name: BackfillVsCodeSettingsUuid
description: Backfills the uuid column of existing vs_code_settings records
feature_category: web_ide
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138355
milestone: '16.7'
queued_migration_version: 20231130140901
finalized_by: 20240222000002
