---
migration_job_name: BackfillPartitionIdCiPipelineConfig
description: Fixes incorrect values for ci_pipelines_config being in the wrong partition
feature_category: continuous_integration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141461
milestone: '16.8'
queued_migration_version: 20240110090352
finalized_by: 20240122133457
