---
data_category: optional
key_path: redis_hll_counters.code_review.i_code_review_user_resolve_conflict_weekly
description: Count of unique users per week who attempt to resolve a conflict through the ui
product_group: code_review
product_categories:
- code_review_workflow
value_type: number
status: active
milestone: "13.12"
time_frame: 7d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_code_review_user_resolve_conflict
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61654
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
