---
data_category: optional
key_path: redis_hll_counters.search.search_total_unique_counts_weekly
description: Calculated unique users to perform Basic or Advanced searches by week
product_group: global_search
product_categories:
- global_search
value_type: number
status: active
time_frame: 7d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
events:
- name: i_search_total
  unique: user.id
- name: i_search_advanced
  unique: user.id
- name: i_search_paid
  unique: user.id
distribution:
- ee
- ce
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
