---
key_path: redis_hll_counters.ci_templates.p_ci_templates_implicit_jobs_deploy_latest_weekly
description: ''
product_group: environments
value_type: number
status: removed
milestone: '14.4'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71157
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_implicit_jobs_deploy_latest
removed_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90163
milestone_removed: '15.5'
