---
data_category: optional
key_path: redis_hll_counters.snippets.i_snippets_show_weekly
description: Weekly number of users viewing snippets
product_group: source_code
value_type: number
status: active
time_frame: 7d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
options:
  events:
  - i_snippets_show
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
