---
key_path: redis_hll_counters.ci_templates.p_ci_templates_implicit_jobs_secret_detection_latest_weekly
description: Weekly counts for implicit use of Secret Detection CI Latest template
  (Jobs folder)
product_group: secret_detection
value_type: number
status: removed
milestone: '15.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/81847
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_implicit_jobs_secret_detection_latest
removed_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90163
milestone_removed: '15.5'
