---
key_path: redis_hll_counters.importer.github_import_project_cancelled_weekly
description: The number of github projects that were cancelled weekly
product_group: import_and_integrate
product_categories:
- importers
value_type: number
status: active
milestone: "15.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113724
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
    - github_import_project_cancelled
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
