---
key_path: redis_hll_counters.ci_templates.p_ci_templates_terraform_module_weekly
description: Count of pipelines using the Terraform Module template
product_group: environments
product_categories:
- infrastructure_as_code
value_type: number
status: active
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110493
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_terraform_module
