---
key_path: redis_hll_counters.user_container_registry.i_container_registry_create_repository_user_weekly
description: A weekly count of users that have created a repository from the registry
product_group: container_registry
product_categories:
- container_registry
value_type: number
status: active
milestone: '15.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107918
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
  - i_container_registry_create_repository_user
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
