# frozen_string_literal: true

module Gitlab
  module PrinciplesDistiller
    class Sync
      module AutoMr
        # MR description has a 1 MB hard limit; multiple per-principle patches
        # may be embedded, so each must stay well under that.
        DIFF_MAX_LINES = 200
        DIFF_MAX_BYTES = 8_192

        def distillation_base_sha
          @distillation_base_sha ||= resolve_distillation_base_sha
        end

        # Returns [text, truncated?]. Caps at DIFF_MAX_LINES or DIFF_MAX_BYTES,
        # whichever hits first.
        def truncate_diff(text)
          lines = text.lines
          truncated = false

          if lines.size > DIFF_MAX_LINES
            lines = lines.first(DIFF_MAX_LINES)
            truncated = true
          end

          result = lines.join
          if result.bytesize > DIFF_MAX_BYTES
            # scrub: byteslice can split a multi-byte char; downstream JSON would blow up otherwise.
            result = result.byteslice(0, DIFF_MAX_BYTES).scrub
            result = result.sub(/[^\n]*\z/, '') # trim partial trailing line
            truncated = true
          end

          [result, truncated]
        end

        def create_branch_and_mr(distilled_contents, affected, auto_mr_cfg)
          # UTC date as identifier; same-day re-runs reuse the branch and
          # update the existing MR (see find_open_mr_iid).
          date = Time.now.utc.strftime('%Y%m%d')
          branch = "#{auto_mr_cfg['branch_prefix']}-#{date}"
          project_id = ENV.fetch(Env::CI_PROJECT_ID) do
            abort Rainbow("ERROR: #{Env::CI_PROJECT_ID} env var is required when --push is given").red
          end
          api_token = ENV.fetch(Env::GITLAB_API_TOKEN) do
            abort Rainbow("ERROR: #{Env::GITLAB_API_TOKEN} not set, cannot create MR").red
          end

          # Branch off origin/<default_branch> (not the current HEAD) so the
          # MR diff contains only the distilled files. The CI before_script
          # fetches origin/<default_branch> for us.
          base_branch = workflow.default_branch
          base_ref = "origin/#{base_branch}"
          system('git', '-C', Workspace.path, 'checkout', '--no-track', '-b', branch, base_ref, exception: true)

          # Writes deferred to here so the publish branch is the only diff.
          paths_to_commit = distilled_contents.map do |name, content|
            path = manifest.principles_path(name)
            File.write(Workspace.join(path), content)
            path
          end

          system('git', '-C', Workspace.path, 'add', '-f', *paths_to_commit, exception: true)

          commit_msg = <<~MSG.chomp
        Update AI development principles from SSOT

        Updated: #{distilled_contents.keys.join(', ')}

        This commit was auto-generated by gitlab-ai-principles-distiller
        based on recent changes to development documentation.
          MSG

          system('git', '-C', Workspace.path, 'commit', '-m', commit_msg, exception: true)
          # --force is safe here: the branch is auto-generated and always
          # rebuilt from origin/<default_branch>, so only our own prior
          # commit can be lost. (--force-with-lease would require a prefetch.)
          system('git', '-C', Workspace.path, 'push', '--force', push_remote_url(api_token, project_id),
            "#{branch}:#{branch}", exception: true)

          prefetch_prior_shas!(affected)

          create_mr(branch, base_branch, project_id, api_token, distilled_contents, affected, date, auto_mr_cfg)
        rescue StandardError => e
          warn Rainbow("ERROR: #{e.message}").red

          base_branch ||= workflow.default_branch

          unless system('git', '-C', Workspace.path, 'checkout', base_branch)
            warn Rainbow("  WARNING: cleanup checkout to #{base_branch} failed; " \
              "you may still be on #{branch}").yellow
          end

          unless system('git', '-C', Workspace.path, 'branch', '-D', branch)
            warn Rainbow("  WARNING: cleanup deletion of branch #{branch} failed; " \
              'remove it manually if unwanted').yellow
          end

          raise
        end

        # Renders the per-principle section embedded in the auto-MR
        # description: principle heading, source-file commit-history links,
        # and a fenced `git diff prior_sha..origin/<default_branch>`.
        def principle_diff_section(name, affected_entry, default_branch)
          sources = affected_entry&.dig(:changed_sources) || []
          prior_sha = affected_entry&.dig(:prior_sha)
          baseline_path = affected_entry&.dig(:config)&.dig('baseline')
          project_url = "#{workflow.gitlab_host}/#{workflow.catalog_project_path}"

          lines = ["#### `#{name}`"]

          if sources.any?
            lines << ''
            lines << "<details><summary>Source files (#{sources.size})</summary>"
            lines << ''
            sources.each do |source|
              path = source['path']
              commits_url = "#{project_url}/-/commits/#{default_branch}/#{path}"
              lines << "- [`#{path}`](#{commits_url})"
            end
            lines << ''
            lines << '</details>'
          end

          paths = sources.map { |s| s['path'] } # -- standalone script without Rails
          paths.unshift(baseline_path) if baseline_path
          diff_text, truncated = compute_principle_diff(prior_sha, default_branch, paths)

          if diff_text
            # 4-backtick fence: ```diff/```ruby blocks inside SSOT files
            # would otherwise close the outer fence early.
            # Resolved SHA (not branch name): range stays meaningful as
            # master moves on.
            target_sha = distillation_base_sha
            lines << ''
            lines << "<details><summary>SSOT diff since previous distillation " \
              "(#{prior_sha[0, 12]} \u2192 #{target_sha[0, 12]})</summary>"
            lines << ''
            lines << '````diff'
            lines << diff_text.chomp

            if truncated
              lines << ''
              lines << "... (diff truncated at #{DIFF_MAX_LINES} lines / #{DIFF_MAX_BYTES / 1024} KB; " \
                'use the per-file commit-history links above for the full picture)'
            end

            lines << '````'
            lines << ''
            lines << '</details>'
          end

          lines.join("\n")
        end

        private

        # CI runners only have origin/<branch>, not a local <branch> ref.
        # Try remote-tracking first, then local, then HEAD as a fallback.
        def resolve_distillation_base_sha
          branch = workflow.default_branch
          ["origin/#{branch}", branch].each do |ref|
            out = IO.popen(['git', '-C', Workspace.path, 'merge-base', 'HEAD', ref],
              err: File::NULL, &:read).strip
            return out unless out.empty?
          end
          IO.popen(['git', '-C', Workspace.path, 'rev-parse', 'HEAD'], err: File::NULL, &:read).strip
        end

        # CI's shallow clone doesn't include prior SHAs from weeks ago.
        # Fetch each unique prior_sha so `git diff <prior_sha>..origin/master`
        # resolves later. Relies on GitLab.com's
        # `uploadpack.allowReachableSHA1InWant=true` for direct-SHA fetches.
        def prefetch_prior_shas!(affected)
          shas = affected.values.filter_map { |entry| entry[:prior_sha] }.uniq
          return if shas.empty?

          shas.each do |sha|
            next if sha_present_locally?(sha)

            puts Rainbow("    prefetching #{sha[0, 12]} for diff embedding...").faint
            success = system('git', '-C', Workspace.path, 'fetch', '--depth=1', 'origin', sha,
              out: File::NULL, err: File::NULL)

            unless success
              warn Rainbow("    WARNING: could not fetch #{sha[0, 12]}; diff embedding will fall back").yellow
            end
          end
        end

        def sha_present_locally?(sha)
          system('git', '-C', Workspace.path, 'cat-file', '-e', "#{sha}^{commit}", out: File::NULL, err: File::NULL)
        end

        # Returns [diff_text, truncated?]. diff_text is nil when prior_sha
        # is unreachable or the diff is empty.
        def compute_principle_diff(prior_sha, default_branch, paths)
          return [nil, false] if prior_sha.nil? || prior_sha.empty? || paths.empty?
          return [nil, false] unless sha_present_locally?(prior_sha)

          target_ref = "origin/#{default_branch}"
          cmd = ['git', '-C', Workspace.path, 'diff', "#{prior_sha}..#{target_ref}", '--', *paths]
          out = IO.popen(cmd, err: File::NULL, &:read)
          return [nil, false] if out.nil? || out.strip.empty?

          truncate_diff(out)
        end

        # Returns the iid of an open MR for the given source branch, or nil.
        # `order_by=created_at&sort=desc` is explicit because the API default
        # is implementation-defined.
        def find_open_mr_iid(encoded_project, source_branch, api_token)
          uri = URI("#{workflow.gitlab_host}/api/v4/projects/#{encoded_project}/merge_requests")
          uri.query = URI.encode_www_form(state: 'opened', source_branch: source_branch,
            order_by: 'created_at', sort: 'desc')

          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = uri.scheme == 'https'
          http.read_timeout = 60

          request = Net::HTTP::Get.new(uri)
          request['PRIVATE-TOKEN'] = api_token
          response = http.request(request)
          return nil unless response.is_a?(Net::HTTPSuccess)

          mrs = JSON.parse(response.body)
          mrs.first&.fetch('iid', nil)
        end

        # Embeds the PAT so `git push` works even when origin is the read-only CI_JOB_TOKEN form.
        def push_remote_url(api_token, project_path_or_id)
          host = URI(workflow.gitlab_host).host || 'gitlab.com'
          # CI_PROJECT_ID is numeric, not usable as a URL path.
          project_path = ENV.fetch(Env::CI_PROJECT_PATH, nil)
          if project_path.nil? || project_path.empty?
            if project_path_or_id.to_s.match?(/\A\d+\z/)
              abort Rainbow("ERROR: #{Env::CI_PROJECT_PATH} env var is required for git push " \
                "(numeric #{Env::CI_PROJECT_ID} alone is not enough)").red
            end

            project_path = project_path_or_id.to_s
          end

          "https://oauth2:#{api_token}@#{host}/#{project_path}.git"
        end

        def create_mr(
          branch, default_branch, project_id, api_token, changed_principles, affected, date,
          auto_mr_cfg)
          sections = changed_principles.keys.map do |name|
            principle_diff_section(name, affected[name], default_branch)
          end.join("\n\n")

          project_url = "#{workflow.gitlab_host}/#{workflow.catalog_project_path}"
          manifest_url = "#{project_url}/-/blob/#{default_branch}/.ai/principles/manifest.yml"
          ci_yml_url = "#{project_url}/-/blob/#{default_branch}/.gitlab/ci/sync-principles.gitlab-ci.yml"

          description = <<~DESC
        ## Summary

        This MR updates AI development principles based on recent changes
        to the development documentation (SSOT).

        ### Updated principles and their source-doc changes

        #{sections}

        ### How this works

        A [scheduled CI job](#{ci_yml_url}) detects changes to `doc/development/`
        files listed in [`.ai/principles/manifest.yml`](#{manifest_url}), then
        uses the GitLab Duo Agent Platform Workflow API to distill updated
        principles for the affected domains.

        Please review the checklist changes to ensure they accurately
        reflect the documentation updates.
          DESC

          encoded_project = URI.encode_www_form_component(project_id)

          # Same-day re-runs update the existing MR in place rather than
          # failing on the 409.
          existing_mr_iid = find_open_mr_iid(encoded_project, branch, api_token)
          body = {
            title: format(auto_mr_cfg['title_template'], date: date),
            description: description,
            labels: Array(auto_mr_cfg['labels']).join(','),
            remove_source_branch: auto_mr_cfg.fetch('remove_source_branch', true)
          }

          host = workflow.gitlab_host
          if existing_mr_iid
            response = workflow.put_json(
              "#{host}/api/v4/projects/#{encoded_project}/merge_requests/#{existing_mr_iid}",
              headers: { 'PRIVATE-TOKEN' => api_token },
              body: body
            )
            action = 'updated'
          else
            response = workflow.post_json(
              "#{host}/api/v4/projects/#{encoded_project}/merge_requests",
              headers: { 'PRIVATE-TOKEN' => api_token },
              body: body.merge(source_branch: branch, target_branch: default_branch)
            )
            action = 'created'
          end

          if response.is_a?(Net::HTTPSuccess)
            puts "\n#{Rainbow("MR #{action}: #{JSON.parse(response.body)['web_url']}").green}"
          else
            abort Rainbow("\nERROR: Failed to #{action.delete_suffix('ed')} MR: " \
              "#{response.code} #{response.body.slice(0, 200)}").red
          end
        end
      end
    end
  end
end
