---
key_path: redis_hll_counters.code_review.i_code_review_user_searches_diff_monthly
description: Count of users who search merge request diffs
product_group: code_review
product_categories:
- code_review_workflow
value_type: number
status: active
milestone: '14.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66522
time_frame: 28d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_code_review_user_searches_diff
data_category: optional
tiers:
  - free
  - premium
  - ultimate
