---
data_category: operational
key_path: redis_hll_counters.ci_templates.p_ci_templates_implicit_auto_devops_monthly
description: Count of pipelines with implicit Auto DevOps runs
product_group: environments
product_categories:
- auto_devops
value_type: number
status: active
time_frame: 28d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
options:
  events:
  - p_ci_templates_implicit_auto_devops
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
performance_indicator_type:
- customer_health_score
