---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.issue_imports.csv
description: Count of (issue) imports from CSV file
product_group: import_and_integrate
product_categories:
- importers
value_type: number
status: active
time_frame: 28d
data_source: database
instrumentation_class: CountCsvImportsMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
