---
key_path: redis_hll_counters.ci_templates.p_ci_templates_scala_monthly
description: ''
product_group: pipeline_authoring
value_type: number
status: active
milestone: '14.3'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/69204
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_scala
