---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.issue_imports.phabricator
description: Count of imports from Phabricator
product_group: import_and_integrate
product_categories:
- importers
value_type: number
status: removed
removed_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117649"
milestone_removed: "16.0"
time_frame: 28d
data_source: database
instrumentation_class: CountImportedProjectsMetric
options:
  import_type: phabricator
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
