---
key_path: redis_hll_counters.testing.i_testing_coverage_report_uploaded_monthly
description: "MAU of coverage test reports uploaded by customers per pipeline"
product_group: pipeline_execution
product_categories:
- code_testing
value_type: number
status: active
milestone: "15.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102371
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_testing_coverage_report_uploaded
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
