---
key_path: redis_hll_counters.ci_templates.p_ci_templates_matlab_monthly
description: ""
product_group: pipeline_authoring
value_type: number
status: active
milestone: "14.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82914
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
    - p_ci_templates_matlab
