---
key_path: redis_hll_counters.ci_templates.p_ci_templates_jobs_sast_latest_monthly
description: Weekly counts for SAST CI Latest template (Jobs folder)
product_group: static_analysis
value_type: number
status: active
milestone: "15.0"
introduced_by_url: 'https://gitlab.com/gitlab-org/gitlab/-/merge_requests/81847'
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
    - p_ci_templates_jobs_sast_latest
