---
key_path: redis_hll_counters.ci_templates.p_ci_templates_opentofu_latest_monthly
description: Count of pipelines that include the OpenTofu pipeline template from GitLab
product_group: environments
value_type: number
status: active
milestone: "16.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142547
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
options:
  events:
    - p_ci_templates_opentofu_latest
