---
name: loose_foreign_keys_clean_job_artifact_files
description: Use a file-aware cleaner for loose foreign key deletion of CI job artifacts to prevent orphaned files on storage.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/604201
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/242769
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/604201
milestone: '19.3'
group: group::pipeline execution
type: ops
default_enabled: false
