---
name: show_diff_if_head_sha_commit_is_missing
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/511302
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177932
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/513174
milestone: '17.8'
group: group::code review
type: ops
default_enabled: true
