---
table_name: deployment_merge_requests
classes:
- DeploymentMergeRequest
feature_categories:
- continuous_delivery
description: https://docs.gitlab.com/ee/ci/environments/index.html#track-newly-included-merge-requests-per-deployment
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18755
milestone: '12.5'
gitlab_schema: gitlab_main_cell
desired_sharding_key:
  project_id:
    references: projects
    backfill_via:
      parent:
        foreign_key: deployment_id
        table: deployments
        sharding_key: project_id
        belongs_to: deployment
table_size: medium
