---
table_name: protected_environment_approval_rules
classes:
- ProtectedEnvironments::ApprovalRule
feature_categories:
- continuous_delivery
description: A rule associated to a protected environment that allows a user, group,
  or role to approve a deployment. See https://docs.gitlab.com/ee/ci/environments/deployment_approvals.html#multiple-approval-rules
  for more details.
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82800
milestone: '14.10'
gitlab_schema: gitlab_main_cell
desired_sharding_key:
  protected_environment_project_id:
    references: projects
    backfill_via:
      parent:
        foreign_key: protected_environment_id
        table: protected_environments
        sharding_key: project_id
        belongs_to: protected_environment
  protected_environment_group_id:
    references: namespaces
    backfill_via:
      parent:
        foreign_key: protected_environment_id
        table: protected_environments
        sharding_key: group_id
        belongs_to: protected_environment
desired_sharding_key_migration_job_name:
- BackfillProtectedEnvironmentApprovalRulesProtectedEnvironmentProjectId
- BackfillProtectedEnvironmentApprovalRulesProtectedEnvironmentGroupId
table_size: small
