---
data_category: optional
key_path: database.version
description: The version of the PostgreSQL database.
product_group: distribution_deploy
product_categories:
- build
value_type: string
status: active
time_frame: none
data_source: system
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
