---
data_category: optional
key_path: settings.operating_system
description: Information about the operating system running GitLab
product_group: distribution_deploy
product_categories:
- build
value_type: string
status: active
milestone: "13.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54778
time_frame: none
data_source: system
instrumentation_class: OperatingSystemMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
