---
data_category: optional
key_path: mattermost_enabled
description: Whether Mattermost is enabled
product_group: import_and_integrate
product_categories:
- integrations
value_type: boolean
status: active
time_frame: none
data_source: system
instrumentation_class: GitlabConfigMetric
options:
  config:
    mattermost: enabled
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/51974
