---
key_path: settings.smtp_encrypted_secrets_enabled
description: Is encrypted SMTP secrets configured?
product_group: distribution_deploy
value_type: boolean
status: active
milestone: "14.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67802
time_frame: none
data_source: system
data_category: optional
instrumentation_class: SmtpEncryptedSecretsMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
