---
data_category: optional
key_path: settings.ldap_encrypted_secrets_enabled
description: Is encrypted LDAP secrets configured?
product_group: distribution_deploy
value_type: boolean
status: active
time_frame: none
data_source: system
instrumentation_class: LdapEncryptedSecretsMetric
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
