---
key_path: settings.service_desk_email_encrypted_secrets_enabled
description: Are service desk email secrets configured?
product_group: distribution_deploy
product_categories:
- build
value_type: boolean
status: active
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108279
time_frame: none
data_source: system
data_category: optional
instrumentation_class: ServiceDeskEmailEncryptedSecretsEnabledMetric
performance_indicator_type: []
distribution:
- ce
- ee
tiers:
- free
- premium
- ultimate
